version: '3'
 
services: 
  
  mysql:
    container_name: mysql
    image: mysql
    networks: 
      - db-net
    volumes: 
      - ./mysql/dbdata:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=fullcycle
      - MYSQL_USER=fullcycle
      - MYSQL_PASSWORD=fullcycle
      - MYSQL_ROOT_PASSWORD=fullcycle
      - LANG=C.UTF-8
    env_file: ./test.env
    command: ["mysqld","--default-authentication-plugin=mysql_native_password"]
  node:
    build :
      context: ./node
    container_name: node
    image: gustavofranca/node
    networks: 
      - desafio-net
      - db-net
    environment: 
    - MYSQL_DATABASE=fullcycle
    - MYSQL_USER=fullcycle
    - MYSQL_PASSWORD=fullcycle
    - DB_HOST=mysql
    depends_on: 
      - mysql
    entrypoint: dockerize -timeout 250s -wait tcp://mysql:3306 docker-entrypoint.sh
    command: node index.js
    env_file: ./test.env
    restart: always
  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    image: gustavofranca/nginx
    networks: 
      - desafio-net
    ports: 
      - 8000:80
    depends_on: 
      - node
    entrypoint: dockerize -timeout 250s -wait tcp://node:3000 /docker-entrypoint.sh
    command: ["nginx", "-g", "daemon off;"]
    restart: always
networks: 
  desafio-net : {}
  db-net: {}
